---
format:
  html: 
    embed-resources: true
echo: true
code-fold: true
title: Lab
author: mimansa dahiya
---

In [1]:
import pandas as pd
import numpy as np

customers = "customers.csv"
orders = "orders.csv"
products = "products.csv"
traffic = "traffic.csv"
competitor_prices = "competitor_prices.html"

# Reading/ Loading

* CSV : pd.read_csv(<file_name>)
* Excel : pd.read_excel(<file_name>)
* JSON : pd.read_json(<file_name>)
* HTML_tables : pd.read_csv_html(<file_name>)
* SQL : pd.read_sql("SELECT.....", connection)
* URL : pd.read_<anyone> ('url')

<anyone> means excel/json/html/sql
<is_just_a_place_holder>, remove <> with path name

In [2]:
cust_data = pd.read_csv(customers)
order_data = pd.read_csv(orders)
prod_data = pd.read_csv(products)
traff_data = pd.read_csv(traffic)
comp_data = pd.read_html(competitor_prices)

ImportError: Missing optional dependency 'lxml'.  Use pip or conda to install lxml.

## Dataframe information

In [ ]:
cust_data.head()

   customer_id first_name             email            phone         city state signup_date
0            1    User001  user001@data.org  +1-555-242-2679     New York    NY  2023-02-26
1            2    User002    user002@biz.co              NaN    Rochester    NY  2023-12-28
2            3    User003  user003@mail.com  +1-555-127-4257     New York    NY  2023-06-08
3            4    User004    user004@biz.co  +1-555-928-1106      Phoenix    AZ  2023-04-20
4            5    User005  user005@data.org  +1-555-320-6514  San Antonio    TX  2023-01-21

In [ ]:
cust_data.dtypes

customer_id     int64
first_name     object
email          object
phone          object
city           object
state          object
signup_date    object
dtype: object

In [ ]:
cust_data.columns

Index(['customer_id', 'first_name', 'email', 'phone', 'city', 'state', 'signup_date'], dtype='object')

In [ ]:
cust_data.describe()

       customer_id
count   120.000000
mean     60.500000
std      34.785054
min       1.000000
25%      30.750000
50%      60.500000
75%      90.250000
max     120.000000

In [ ]:
cust_data["state"].nunique()

8

In [ ]:
cust_data["state"].unique()

array(['NY', 'AZ', 'TX', 'IL', 'WA', 'FL', 'CA', 'MA'], dtype=object)

#### duplicates

In [ ]:
cust_data['state'].duplicated() #check duplicates, true means that row has duplicated state value
# cust_data['state'].duplicated().sum() ; this just checks the sum of all missing values in state

0      False
1       True
2       True
3      False
4      False
       ...
115     True
116     True
117     True
118     True
119     True
Name: state, Length: 120, dtype: bool

In [ ]:
cust_data.drop_duplicates()

     customer_id first_name                email            phone         city state signup_date
0              1    User001     user001@data.org  +1-555-242-2679     New York    NY  2023-02-26
1              2    User002       user002@biz.co              NaN    Rochester    NY  2023-12-28
2              3    User003     user003@mail.com  +1-555-127-4257     New York    NY  2023-06-08
3              4    User004       user004@biz.co  +1-555-928-1106      Phoenix    AZ  2023-04-20
4              5    User005     user005@data.org  +1-555-320-6514  San Antonio    TX  2023-01-21
..           ...        ...                  ...              ...          ...   ...         ...
115          116    User116  user116@example.com  +1-555-561-4995      Chicago    IL  2023-09-04
116          117    User117     user117@data.org              NaN    Cambridge    MA  2023-07-15
117          118    User118       user118@biz.co  +1-555-916-5232      Chicago    IL  2023-01-25
118          119    User119     user119@data.org  +1-555-629-4130     Evanston    IL  2023-09-25
119          120    User120       user120@biz.co  +1-555-876-4937     New York    NY  2023-04-04

[120 rows x 7 columns]

##### rename

In [ ]:
cust_data['state'].rename

<bound method Series.rename of 0      NY
1      NY
2      NY
3      AZ
4      TX
       ..
115    IL
116    MA
117    IL
118    IL
119    NY
Name: state, Length: 120, dtype: object>

In [ ]:
cust_data['state'] = cust_data['state'].replace({
    "CA": "CAL"
    "NY": "NEW YORK"
})
#cust_data = cust_data.rename(solumns={'state:})

SyntaxError: invalid syntax (1984068359.py, line 3)

In [ ]:
order_data.dtypes

order_id          int64
customer_id       int64
product_id        int64
order_ts         object
quantity          int64
discount_pct    float64
channel          object
coupon_code      object
dtype: object

In [ ]:
cust_data['s_date']= pd.to_datetime(cust_data['signup_date'])
cust_data.head()

   customer_id first_name             email  ... state signup_date     s_date
0            1    User001  user001@data.org  ...    NY  2023-02-26 2023-02-26
1            2    User002    user002@biz.co  ...    NY  2023-12-28 2023-12-28
2            3    User003  user003@mail.com  ...    NY  2023-06-08 2023-06-08
3            4    User004    user004@biz.co  ...    AZ  2023-04-20 2023-04-20
4            5    User005  user005@data.org  ...    TX  2023-01-21 2023-01-21

[5 rows x 8 columns]

#### Select Columns and Filtering Rows

In [ ]:
#column selection
order_sel = order_data[['order_id', 'customer_id']]
order_sel

     order_id  customer_id
0           1           89
1           2           52
2           3           96
3           4           93
4           5           28
..        ...          ...
795       796           43
796       797           54
797       798          116
798       799          111
799       800          112

[800 rows x 2 columns]

In [ ]:
#query 
orders_filter = order_data.query("quantity == 3 & coupon_code.notna()").head()
orders_filter
#a query in a long string
# and / & ; both work
# query is like an if condition, in quotes
# can use; == / <= / >=...

    order_id  customer_id  product_id  ... discount_pct  channel  coupon_code
6          7           36           1  ...         0.30      web        VIP20
7          8           14           1  ...         0.14      web     FREESHIP
9         10           20           3  ...         0.04      web    holiday10
23        24           98           9  ...         0.16      web        VIP20
33        34           59           6  ...         0.02      web       SAVE10

[5 rows x 8 columns]

In [ ]:
# loc, iloc
new_table = order_data.loc[:6,['order_id', 'customer_id']]  # :6 is row, ['order_id', 'customer_id'] is column
new_table

   order_id  customer_id
0         1           89
1         2           52
2         3           96
3         4           93
4         5           28
5         6           13
6         7           36

In [ ]:
my_row = order_data.iloc[0]  #iloc is index location; usually not used
my_row

order_id                          1
customer_id                      89
product_id                        8
order_ts        2024-11-26T22:31:00
quantity                          1
discount_pct                    0.1
channel                         web
coupon_code                     NaN
Name: 0, dtype: object

In [ ]:
my_row = order_data.iloc[:5] 
my_row

   order_id  customer_id  product_id  ... discount_pct  channel  coupon_code
0         1           89           8  ...         0.10      web          NaN
1         2           52           4  ...         0.19   mobile          NaN
2         3           96           9  ...         0.09      web          NaN
3         4           93           4  ...         0.21    store          NaN
4         5           28           8  ...         0.17   mobile          NaN

[5 rows x 8 columns]

#### Sorting

In [ ]:
order_sort = order_data.sort_values(['quantity', 'discount_pct'],   # sorting the column values; 
ascending = [False, True])
order_sort

     order_id  customer_id  product_id  ... discount_pct  channel  coupon_code
399       400           98           9  ...         0.13      web          NaN
130       131           50           6  ...         0.23      web          NaN
326       327          116           1  ...         0.24      web       SAVE10
356       357           73           9  ...         0.27      web          NaN
267       268          102           7  ...         0.04      web          NaN
..        ...          ...         ...  ...          ...      ...          ...
742       743           38          10  ...          NaN   mobile     FREESHIP
755       756           29           5  ...          NaN      web      WELCOME
772       773          107           8  ...          NaN    store          NaN
777       778           15           8  ...          NaN      web          NaN
795       796           43           3  ...          NaN      web        VIP20

[800 rows x 8 columns]

## Missing Values

In [ ]:
cust_data.isna().sum() #gives us number of missing values

customer_id     0
first_name      0
email           0
phone          17
city            0
state           0
signup_date     0
dtype: int64

In [ ]:
cust_data.isna().mean() # average mean of missing values
# 14% of phone columns values are missing

customer_id    0.000000
first_name     0.000000
email          0.000000
phone          0.141667
city           0.000000
state          0.000000
signup_date    0.000000
dtype: float64

In [ ]:
cust_data['phone'].fillna('+1-000-000-0000') # fillna adds '000-000-0000' in the phone column
 # but original data set still has null values 
# to change the original dataset, we need to equate the fillna function to the original dataset

0      +1-555-242-2679
1         000-000-0000
2      +1-555-127-4257
3      +1-555-928-1106
4      +1-555-320-6514
            ...
115    +1-555-561-4995
116       000-000-0000
117    +1-555-916-5232
118    +1-555-629-4130
119    +1-555-876-4937
Name: phone, Length: 120, dtype: object

In [ ]:
cust_data['phone'] = cust_data['phone'].fillna('+1-000-000-0000')
print(cust_data['phone'])
#now we the actual dataframe

0      +1-555-242-2679
1         000-000-0000
2      +1-555-127-4257
3      +1-555-928-1106
4      +1-555-320-6514
            ...
115    +1-555-561-4995
116       000-000-0000
117    +1-555-916-5232
118    +1-555-629-4130
119    +1-555-876-4937
Name: phone, Length: 120, dtype: object

In [ ]:
copy_ord = order_data #made a copy of original data

In [ ]:
copy_ord.isna().sum() #sum of missing values

order_id          0
customer_id       0
product_id        0
order_ts          0
quantity          0
discount_pct     82
channel           0
coupon_code     604
dtype: int64

In [ ]:
copy_ord.info()

<class 'pandas.core.frame.DataFrame'>
Index: 177 entries, 6 to 796
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   order_id      177 non-null    int64
 1   customer_id   177 non-null    int64
 2   product_id    177 non-null    int64
 3   order_ts      177 non-null    object
 4   quantity      177 non-null    int64
 5   discount_pct  177 non-null    float64
 6   channel       177 non-null    object
 7   coupon_code   177 non-null    object
dtypes: float64(1), int64(4), object(3)
memory usage: 12.4+ KB

In [ ]:
copy_ord

     order_id  customer_id  product_id  ... discount_pct  channel  coupon_code
0           1           89           8  ...         0.10      web          NaN
1           2           52           4  ...         0.19   mobile          NaN
2           3           96           9  ...         0.09      web          NaN
3           4           93           4  ...         0.21    store          NaN
4           5           28           8  ...         0.17   mobile          NaN
..        ...          ...         ...  ...          ...      ...          ...
795       796           43           3  ...          NaN      web        VIP20
796       797           54           3  ...         0.17      web    holiday10
797       798          116           3  ...         0.26      web          NaN
798       799          111           4  ...         0.07      web          NaN
799       800          112           4  ...         0.17    store          NaN

[800 rows x 8 columns]

In [ ]:
copy_ord=copy_ord.dropna()

In [ ]:
copy_ord.isna().sum()

order_id          0
customer_id       0
product_id        0
order_ts          0
quantity          0
discount_pct     82
channel           0
coupon_code     604
dtype: int64

#### Mutating and Transdforming

In [ ]:
order_enrich = order_data.merge (prod_data[['product_id', 
'unit_price']], on = 
'product_id', how ='left')
order_enrich

     order_id  customer_id  product_id             order_ts  quantity  discount_pct channel coupon_code  unit_price
0           1           89           8  2024-11-26T22:31:00         1          0.10     web         NaN       24.99
1           2           52           4  2024-06-05T21:37:00         1          0.19  mobile         NaN       49.00
2           3           96           9  2024-06-18T11:44:00         1          0.09     web         NaN        7.49
3           4           93           4  2024-06-10T03:47:00         1          0.21   store         NaN       49.00
4           5           28           8  2024-05-21T23:37:00         1          0.17  mobile         NaN       24.99
..        ...          ...         ...                  ...       ...           ...     ...         ...         ...
795       796           43           3  2024-01-17T22:36:00         1           NaN     web       VIP20       29.99
796       797           54           3  2024-06-24T07:56:00         3          0.17     web   holiday10       29.99
797       798          116           3  2024-10-22T17:54:00         2          0.26     web         NaN       29.99
798       799          111           4  2024-10-29T15:53:00         2          0.07     web         NaN       49.00
799       800          112           4  2024-05-06T10:27:00         3          0.17   store         NaN       49.00

[800 rows x 9 columns]

In [ ]:
order_enrich = order_enrich.assign(
    gross_rev = lambda d: d['unit_price'] * d['quantity'],
    net_rev = lambda d: d['gross_rev'] * (1 - d['discount_pct'])
    ) 

order_enrich.head()

   order_id  customer_id  product_id             order_ts  quantity  ...  channel coupon_code unit_price  gross_rev  net_rev
0         1           89           8  2024-11-26T22:31:00         1  ...      web         NaN      24.99      24.99  22.4910
1         2           52           4  2024-06-05T21:37:00         1  ...   mobile         NaN      49.00      49.00  39.6900
2         3           96           9  2024-06-18T11:44:00         1  ...      web         NaN       7.49       7.49   6.8159
3         4           93           4  2024-06-10T03:47:00         1  ...    store         NaN      49.00      49.00  38.7100
4         5           28           8  2024-05-21T23:37:00         1  ...   mobile         NaN      24.99      24.99  20.7417

[5 rows x 11 columns]

In [ ]:
order_enrich

     order_id  customer_id  product_id             order_ts  quantity  ...  channel coupon_code unit_price  gross_rev   net_rev
0           1           89           8  2024-11-26T22:31:00         1  ...      web         NaN      24.99      24.99   22.4910
1           2           52           4  2024-06-05T21:37:00         1  ...   mobile         NaN      49.00      49.00   39.6900
2           3           96           9  2024-06-18T11:44:00         1  ...      web         NaN       7.49       7.49    6.8159
3           4           93           4  2024-06-10T03:47:00         1  ...    store         NaN      49.00      49.00   38.7100
4           5           28           8  2024-05-21T23:37:00         1  ...   mobile         NaN      24.99      24.99   20.7417
..        ...          ...         ...                  ...       ...  ...      ...         ...        ...        ...       ...
795       796           43           3  2024-01-17T22:36:00         1  ...      web       VIP20      29.99      29.99       NaN
796       797           54           3  2024-06-24T07:56:00         3  ...      web   holiday10      29.99      89.97   74.6751
797       798          116           3  2024-10-22T17:54:00         2  ...      web         NaN      29.99      59.98   44.3852
798       799          111           4  2024-10-29T15:53:00         2  ...      web         NaN      49.00      98.00   91.1400
799       800          112           4  2024-05-06T10:27:00         3  ...    store         NaN      49.00     147.00  122.0100

[800 rows x 11 columns]

In [ ]:
order_enrich

     order_id  customer_id  product_id             order_ts  quantity  ...  channel coupon_code unit_price  gross_rev   net_rev
0           1           89           8  2024-11-26T22:31:00         1  ...      web         NaN      24.99      24.99   22.4910
1           2           52           4  2024-06-05T21:37:00         1  ...   mobile         NaN      49.00      49.00   39.6900
2           3           96           9  2024-06-18T11:44:00         1  ...      web         NaN       7.49       7.49    6.8159
3           4           93           4  2024-06-10T03:47:00         1  ...    store         NaN      49.00      49.00   38.7100
4           5           28           8  2024-05-21T23:37:00         1  ...   mobile         NaN      24.99      24.99   20.7417
..        ...          ...         ...                  ...       ...  ...      ...         ...        ...        ...       ...
795       796           43           3  2024-01-17T22:36:00         1  ...      web       VIP20      29.99      29.99       NaN
796       797           54           3  2024-06-24T07:56:00         3  ...      web   holiday10      29.99      89.97   74.6751
797       798          116           3  2024-10-22T17:54:00         2  ...      web         NaN      29.99      59.98   44.3852
798       799          111           4  2024-10-29T15:53:00         2  ...      web         NaN      49.00      98.00   91.1400
799       800          112           4  2024-05-06T10:27:00         3  ...    store         NaN      49.00     147.00  122.0100

[800 rows x 11 columns]

# Mapping and applying

In [ ]:
print(order_enrich['channel'].unique()) #checked the values of column

['web' 'mobile' 'store']

In [ ]:
name_map={
    'web':'Web',
    'mobile': 'Mobile App',
    'store': 'Retail Store'
}
name_map['store']

'Retail Store'

In [ ]:
order_enrich['channel_better']= order_enrich['channel'].astype(str).map(name_map) 
order_enrich.head(3)

   order_id  customer_id  product_id             order_ts  quantity  ...  coupon_code unit_price gross_rev  net_rev  channel_better
0         1           89           8  2024-11-26T22:31:00         1  ...          NaN      24.99     24.99  22.4910               1
1         2           52           4  2024-06-05T21:37:00         1  ...          NaN      49.00     49.00  39.6900               2
2         3           96           9  2024-06-18T11:44:00         1  ...          NaN       7.49      7.49   6.8159               1

[3 rows x 12 columns]

In [ ]:
order_enrich['coupon_code'].unique()

array([nan, 'VIP20', 'FREESHIP', 'holiday10', 'WELCOME', 'SAVE10'], dtype=object)

In [ ]:
order_enrich['coupon_code']=order_enrich['coupon_code'].replace({
    'holiday10': 'HOLIDAY10',
    'Holiday10': 'HOLIDAY10'
})
order_enrich['coupon_code'].unique()

array([nan, 'VIP20', 'FREESHIP', 'HOLIDAY10', 'WELCOME', 'SAVE10'], dtype=object)

### Apply

In [ ]:
def is_big_order(row):
    return((row['quantity']>=3) and (row['net_rev']>=60))
order_enrich ['big_order']= order_enrich.apply(is_big_order, axis=1) #axis=1 column wise

order_enrich.head()

   order_id  customer_id  product_id             order_ts  quantity  ...  unit_price gross_rev  net_rev  channel_better  big_order
0         1           89           8  2024-11-26T22:31:00         1  ...       24.99     24.99  22.4910               1      False
1         2           52           4  2024-06-05T21:37:00         1  ...       49.00     49.00  39.6900               2      False
2         3           96           9  2024-06-18T11:44:00         1  ...        7.49      7.49   6.8159               1      False
3         4           93           4  2024-06-10T03:47:00         1  ...       49.00     49.00  38.7100               3      False
4         5           28           8  2024-05-21T23:37:00         1  ...       24.99     24.99  20.7417               2      False

[5 rows x 13 columns]

# Summarize and aggregate

In [ ]:
order_enrich['order_ts']=pd.to_datetime(order_enrich['order_ts'])
order_enrich['order_ts'].dt.month

0      11
1       6
2       6
3       6
4       5
       ..
795     1
796     6
797    10
798    10
799     5
Name: order_ts, Length: 800, dtype: int32

###

In [ ]:
monthly = (order_enrich.groupby(
    [order_enrich['order_ts'].dt.month, 'channel']).agg(
        order = ('order_id', 'count'),
        qty = ('quantity', 'sum'),
        gross = ('gross_rev', 'sum'),
        net = ('net_rev', 'sum')).reset_index().rename(columns = {'order_ts' : 'month'})
)
monthly.head()

   month channel  order  qty    gross        net
0      1  mobile     12   20   617.32   411.6649
1      1   store     26   54  1569.14  1295.6232
2      1     web     35   75  2221.37  1610.0299
3      2  mobile     15   25   616.29   505.9620
4      2   store     17   33   918.75   620.5831

In [ ]:
monthly.isna().any()

month      False
channel    False
order      False
qty        False
gross      False
net        False
dtype: bool

In [ ]:
pivoted = monthly.pivot(index = 'month', columns = 'channel', values ='net')
print(pivoted)

#index=row
#column=column


pivoted_filled = pivoted.fillna(0)
print(pivoted_filled)

channel    mobile      store        web
month
1        411.6649  1295.6232  1610.0299
2        505.9620   620.5831  1628.3948
3        343.9385   612.0582  1208.6417
4        374.2054   587.4709  1376.1291
5        557.2474   636.1117  1334.0767
6        437.0913   466.4271  1085.6976
7        334.7094   527.0300  1206.3939
8        251.6669  1031.6039  1052.6182
9        600.4629   693.2412  1782.6593
10       653.8543   884.5382  1490.5564
11       920.2776   606.6200  1118.0994
12       348.3082   660.9217  1514.2557
channel    mobile      store        web
month
1        411.6649  1295.6232  1610.0299
2        505.9620   620.5831  1628.3948
3        343.9385   612.0582  1208.6417
4        374.2054   587.4709  1376.1291
5        557.2474   636.1117  1334.0767
6        437.0913   466.4271  1085.6976
7        334.7094   527.0300  1206.3939
8        251.6669  1031.6039  1052.6182
9        600.4629   693.2412  1782.6593
10       653.8543   884.5382  1490.5564
11       920.2776   606.6200  1118.0994
12       348.3082   660.9217  1514.2557

In [ ]:
long_again = pivoted_filled.reset_index().melt(id_vars='month', var_name= 'channel', value_name = 'net')

print(pivoted_filled.head())
print(long_again.sort_values('month').reset_index(drop=True).head())

channel    mobile      store        web
month
1        411.6649  1295.6232  1610.0299
2        505.9620   620.5831  1628.3948
3        343.9385   612.0582  1208.6417
4        374.2054   587.4709  1376.1291
5        557.2474   636.1117  1334.0767
   month channel        net
0      1  mobile   411.6649
1      1     web  1610.0299
2      1   store  1295.6232
3      2  mobile   505.9620
4      2     web  1628.3948